import type { Metadata } from "next";
import { LegalPage } from "../components/legal/LegalPage";
export const metadata: Metadata = { title: "Zasady aukcji", description: "Jak działają aukcje Fiszy." };
export default function Page() { return <LegalPage eyebrow="Mechanika" title="Zasady aukcji" lead="Przejrzyste zasady wejścia, spadającej ceny, kolejki zakupu i finalizacji zamówienia." sections={[
  { title: "Przed startem", bullets: ["Udział jest dostępny wyłącznie dla osób, które ukończyły 18 lat.", "Każda runda pokazuje własny czas startu, cenę początkową, cenę minimalną, wysokość obniżki, interwał i opłatę za wejście.", "Wejście można opłacić do chwili rozpoczęcia rundy; dotyczy ono jednej konkretnej edycji i nie przechodzi na następną."] },
  { title: "Gdy cena spada", paragraphs: ["Cena początkowa odpowiada rynkowej wartości produktu, a minimalna wynosi 1 zł. Cena obniża się zgodnie z parametrami pokazanymi przy danej aukcji. Rozstrzygający jest zapis po stronie serwera, nie zegar urządzenia użytkownika."] },
  { title: "Kliknięcie i kolejka", paragraphs: ["Po kliknięciu serwer zapisuje cenę widoczną w tej chwili oraz kolejność zgłoszenia. Pierwsza osoba w kolejce otrzymuje możliwość płatności; późniejsze poprawne kliknięcia zachowują miejsce i swoją cenę. Aukcja oraz spadek ceny trwają dalej."], bullets: ["Nie można przeskoczyć kolejki odświeżaniem strony ani ponownym klikaniem.", "Nieaktualna cena jest odrzucana, aby każdy uczestnik wiedział, za jaką kwotę podejmuje decyzję."] },
  { title: "Płatność", paragraphs: ["Osoba, której kolej przypada, ma 2 minuty na ukończenie płatności. Jeśli płatność nie zostanie zakończona lub zostanie anulowana, szansa przechodzi do następnej osoby w kolejce. Aktualnie płatności obsługuje Stripe."] },
  { title: "Unieważnienie i zwrot", paragraphs: ["Jeżeli aukcja zostanie unieważniona z przyczyn niezależnych od uczestnika, opłata za wejście zostanie zwrócona w ciągu 7 dni. W przypadku osoby, która nie dołączyła do aukcji, opłata za wejście nie jest pobierana."] },
]} />; }
