import type { Metadata } from "next";
import { LegalPage } from "../components/legal/LegalPage";
export const metadata: Metadata = { title: "Regulamin | Fiszy", description: "Zasady korzystania z portalu Fiszy, aukcji, płatności oraz realizacji zamówień." };
export default function Page() { return <LegalPage eyebrow="Dokumenty" title="Regulamin portalu" lead="Najważniejsze zasady konta, korzystania z serwisu, płatności i odpowiedzialności stron." sections={[
  { title: "1. Zakres usługi", paragraphs: ["Fiszy jest prowadzonym przez Jakuba Rybę portalem aukcji z malejącą ceną. Fiszy sprzedaje produkty z własnego stocku. Regulamin określa zasady korzystania z konta, udziału w aukcjach, płatności oraz realizacji zamówień.", "Korzystanie z konta wymaga zaakceptowania regulaminu i polityki prywatności w wersji obowiązującej w chwili czynności."] },
  { title: "2. Konto użytkownika", bullets: ["Udział w aukcjach jest przeznaczony wyłącznie dla osób, które ukończyły 18 lat; potwierdzenie wieku jest wymagane przed płatnością.", "Konto można utworzyć adresem e-mail lub obsługiwanym dostawcą logowania.", "Użytkownik odpowiada za bezpieczeństwo swojego sposobu logowania i prawdziwość danych dostawy.", "Jedna osoba nie może używać wielu kont do obchodzenia limitów lub wpływania na wynik aukcji."] },
  { title: "3. Aukcje i opłaty", paragraphs: ["Szczegółowe reguły wejścia, spadku ceny, kolejki zakupu i czasu na zapłatę opisują Zasady aukcji. Przed potwierdzeniem płatności użytkownik widzi cenę, opłatę i wymagane działanie."], bullets: ["Cena i czas są ustalane przez serwer.", "Kliknięcie zapisuje cenę i pozycję w kolejce zakupu.", "Nieudana lub anulowana płatność nie tworzy opłaconego zamówienia."] },
  { title: "4. Zamówienie i dostawa", paragraphs: ["Po potwierdzeniu płatności powstaje zamówienie. Dostawa na terenie Polski jest bezpłatna i realizowana przez InPost. Status realizacji, numer przesyłki i kontakt z obsługą są dostępne w Moje Fiszy."] },
  { title: "5. Reklamacje, odstąpienie i zwroty", paragraphs: ["Uprawnienia konsumenta nie są ograniczane przez mechanikę aukcji. Procedura zależy od rodzaju produktu i podstawy zgłoszenia; szczegóły zawiera strona Reklamacje."] },
  { title: "6. Niedozwolone działania", bullets: ["automatyczne klikanie, boty i próby przeciążenia", "podszywanie się pod inną osobę", "manipulowanie płatnością, czasem lub komunikacją z API", "wykorzystywanie błędów zamiast ich zgłoszenia"] },
  { title: "7. Zmiany i kontakt", paragraphs: ["Istotne zmiany regulaminu będą komunikowane z wyprzedzeniem. Pytania i zgłoszenia można przesłać w centrum pomocy po zalogowaniu."] },
]} />; }
