export const clerkAppearance = {
  variables: {
    colorPrimary: "#7b2cff",
    colorForeground: "#f8f7fb",
    colorMutedForeground: "#aaa6b2",
    colorBackground: "#111114",
    colorInputBackground: "#0c0c0e",
    colorInputForeground: "#f8f7fb",
    colorBorder: "rgba(255, 255, 255, 0.14)",
    colorDanger: "#ff7665",
    colorSuccess: "#72d69a",
    borderRadius: "0.875rem",
    fontFamily: "var(--font-geist-sans), Arial, sans-serif",
    fontWeight: { normal: 400, medium: 500, semibold: 600, bold: 650 },
  },
  options: {
    socialButtonsPlacement: "top" as const,
    socialButtonsVariant: "blockButton" as const,
    privacyPageUrl: "/prywatnosc",
    unsafe_disableDevelopmentModeWarnings: true,
  },
  elements: {
    rootBox: { width: "100%" },
    cardBox: { width: "100%", boxShadow: "none" },
    card: {
      width: "100%",
      border: "1px solid rgba(255,255,255,.12)",
      borderRadius: "24px",
      background: "#111114",
      boxShadow: "0 28px 90px rgba(0,0,0,.34)",
      padding: "clamp(24px, 5vw, 40px)",
    },
    headerTitle: { color: "#f8f7fb", fontSize: "1.75rem", fontWeight: 600, letterSpacing: "-.04em" },
    headerSubtitle: { color: "#aaa6b2", fontSize: ".9rem" },
    socialButtonsBlockButton: {
      minHeight: "48px",
      border: "1px solid rgba(255,255,255,.14)",
      background: "#18181c",
      color: "#f8f7fb",
      boxShadow: "none",
      fontWeight: 550,
    },
    socialButtonsBlockButtonText: { color: "#f8f7fb", fontWeight: 550 },
    dividerLine: { background: "rgba(255,255,255,.12)" },
    dividerText: { color: "#7f7b88", fontSize: ".72rem" },
    formFieldLabel: { color: "#c8c4cf", fontSize: ".78rem", fontWeight: 500 },
    formFieldInput: {
      minHeight: "48px",
      border: "1px solid rgba(255,255,255,.15)",
      background: "#0c0c0e",
      color: "#f8f7fb",
      boxShadow: "none",
    },
    formButtonPrimary: {
      minHeight: "48px",
      background: "#7b2cff",
      color: "#fff",
      boxShadow: "none",
      fontSize: ".88rem",
      fontWeight: 600,
    },
    footer: { background: "transparent" },
    footerActionText: { color: "#8f8b97" },
    footerActionLink: { color: "#b995ff", fontWeight: 600 },
    identityPreview: { borderColor: "rgba(255,255,255,.12)", background: "#18181c" },
    identityPreviewText: { color: "#f8f7fb" },
    identityPreviewEditButton: { color: "#b995ff" },
    alert: { borderColor: "rgba(255,118,101,.38)", background: "rgba(255,118,101,.1)" },
    formFieldErrorText: { color: "#ff9385" },
    backLink: { color: "#b995ff" },
    formResendCodeLink: { color: "#b995ff" },
  },
};
