export type LegalDocumentVersion = {
  id: string;
  title: string;
  version: string;
  effectiveAt: string;
  publishedAt: string;
  status: "active" | "archived";
  fileName: string;
  content: string;
};

const EFFECTIVE_AT = "2026-09-27T00:00:00+02:00";

function snapshot(id: string) {
  const snapshots: Record<string, string> = {
    regulamin: `# Regulamin portalu Fiszy\n\nWersja 1.0 · obowiązuje od 27.09.2026\n\n## 1. Zakres usługi\nFiszy jest prowadzonym przez Jakuba Rybę portalem aukcji z malejącą ceną. Fiszy sprzedaje produkty z własnego stocku. Regulamin określa zasady konta, aukcji, płatności i realizacji zamówień.\n\n## 2. Konto użytkownika\nUdział jest przeznaczony wyłącznie dla osób, które ukończyły 18 lat. Użytkownik odpowiada za bezpieczeństwo logowania i prawdziwość danych dostawy. Jedna osoba nie może używać wielu kont do obchodzenia limitów.\n\n## 3. Aukcje i opłaty\nCena i czas są ustalane przez serwer. Kliknięcie zapisuje cenę oraz pozycję w kolejce zakupu. Nieudana lub anulowana płatność nie tworzy opłaconego zamówienia.\n\n## 4. Zamówienie i dostawa\nPo potwierdzeniu płatności powstaje zamówienie. Dostawa na terenie Polski jest bezpłatna i realizowana przez InPost.\n\n## 5. Reklamacje, odstąpienie i zwroty\nUprawnienia konsumenta nie są ograniczane przez mechanikę aukcji.\n\n## 6. Niedozwolone działania\nZakazane są automatyczne klikanie, boty, podszywanie się, manipulowanie płatnością, czasem lub API oraz wykorzystywanie błędów zamiast ich zgłoszenia.\n\n## 7. Zmiany i kontakt\nIstotne zmiany regulaminu będą komunikowane z wyprzedzeniem.`,
    "zasady-aukcji": `# Zasady aukcji Fiszy\n\nWersja 1.0 · obowiązuje od 27.09.2026\n\n## Przed startem\nUdział jest dostępny wyłącznie dla osób 18+. Każda runda pokazuje czas startu, cenę początkową, cenę minimalną, wysokość obniżki, interwał i opłatę za wejście.\n\n## Gdy cena spada\nCena początkowa odpowiada rynkowej wartości produktu, a minimalna wynosi 1 zł. Rozstrzygający jest zapis serwera.\n\n## Kliknięcie i kolejka\nSerwer zapisuje cenę widoczną w chwili kliknięcia oraz kolejność zgłoszenia. Późniejsze poprawne kliknięcia zachowują miejsce i swoją cenę, a aukcja i spadek ceny trwają dalej.\n\n## Płatność\nOsoba, której przypada kolej, ma 2 minuty na ukończenie płatności przez Stripe. Gdy płatność nie zostanie zakończona lub zostanie anulowana, szansa przechodzi do kolejnej osoby.\n\n## Unieważnienie i zwrot\nJeżeli aukcja zostanie unieważniona z przyczyn niezależnych od uczestnika, opłata za wejście zostanie zwrócona w ciągu 7 dni.`,
    prywatnosc: `# Polityka prywatności Fiszy\n\nWersja 1.0 · obowiązuje od 27.09.2026\n\n## Administrator\nAdministratorem danych jest Jakub Ryba — właściciel Fiszy. Kontakt: rodo@fiszy.pl.\n\n## Dane i cel\nPrzetwarzamy adres e-mail, informacje o zgodzie, źródle wejścia oraz ograniczone dane techniczne potrzebne do ochrony przed nadużyciami. Dane służą informowaniu o starcie aukcji, bezpieczeństwu oraz obsłudze konta i zamówienia.\n\n## Odbiorcy, okres i prawa\nDane mogą być przetwarzane przez dostawców hostingu, przechowywania danych, logowania, poczty i płatności, wyłącznie w niezbędnym zakresie. Możesz żądać dostępu, sprostowania, usunięcia, ograniczenia, przeniesienia danych lub wnieść sprzeciw; przysługuje też skarga do Prezesa UODO.`,
    cookies: `# Cookies i podobne technologie\n\nWersja 1.0 · obowiązuje od 27.09.2026\n\n## Niezbędne\nCookies sesyjne umożliwiają logowanie, bezpieczeństwo, ochronę przed nadużyciami i ustawienia wymagane do działania serwisu.\n\n## Analityka\nVercel Web Analytics i Speed Insights mierzą działanie oraz wydajność. Dobrowolna analityka jest używana zgodnie z wyborem użytkownika.\n\n## Zarządzanie\nUstawienia przeglądarki mogą usuwać lub blokować cookies, co może wylogować użytkownika.`,
    reklamacje: `# Reklamacje i zwroty Fiszy\n\nWersja 1.0 · obowiązuje od 27.09.2026\n\n## Zgłoszenie\nSprawę zgłasza się w Moje Fiszy → Pomoc i reklamacje, podając numer zamówienia oraz opis oczekiwanego rozwiązania.\n\n## Reklamacja produktu\nNależy opisać wadę, datę jej zauważenia i informacje pozwalające zidentyfikować zamówienie.\n\n## Odstąpienie konsumenta\nKonsument może odstąpić od umowy w terminie 14 dni od otrzymania produktu, z wyjątkami przewidzianymi przez prawo. Koszt odesłania produktu ponosi konsument, chyba że uzgodnimy inaczej.\n\n## Płatność i terminy\nKażdy zwrot jest uzgadniany z referencją operatora płatności, rundą i kontem. Potwierdzamy zgłoszenie i odpowiadamy w terminie wymaganym przez przepisy.`,
  };
  return snapshots[id] ?? "";
}

export const legalDocumentHistory: LegalDocumentVersion[] = ([
  { id: "regulamin", title: "Regulamin portalu", version: "1.0", effectiveAt: EFFECTIVE_AT, publishedAt: EFFECTIVE_AT, status: "active", fileName: "fiszy-regulamin-v1.0-2026-09-27.md", content: "# Regulamin portalu Fiszy\n\nWersja 1.0 · obowiązuje od 27.09.2026\n\nFiszy jest portalem aukcji z malejącą ceną, prowadzonym przez Jakuba Rybę. Udział jest przeznaczony dla osób 18+. Dostawa InPost na terenie Polski jest bezpłatna. Szczegóły mechaniki opisują Zasady aukcji." },
  { id: "zasady-aukcji", title: "Zasady aukcji", version: "1.0", effectiveAt: EFFECTIVE_AT, publishedAt: EFFECTIVE_AT, status: "active", fileName: "fiszy-zasady-aukcji-v1.0-2026-09-27.md", content: "# Zasady aukcji Fiszy\n\nWersja 1.0 · obowiązuje od 27.09.2026\n\nCena startowa odpowiada wartości rynkowej, a cena minimalna wynosi 1 zł. Serwer zapisuje cenę i kolejność kliknięcia. Osoba, której przypada kolej, ma 2 minuty na płatność Stripe; po nieudanej płatności szansa przechodzi do następnej osoby w kolejce." },
  { id: "prywatnosc", title: "Polityka prywatności", version: "1.0", effectiveAt: EFFECTIVE_AT, publishedAt: EFFECTIVE_AT, status: "active", fileName: "fiszy-polityka-prywatnosci-v1.0-2026-09-27.md", content: "# Polityka prywatności Fiszy\n\nWersja 1.0 · obowiązuje od 27.09.2026\n\nAdministratorem danych jest Jakub Ryba — właściciel Fiszy. Kontakt: rodo@fiszy.pl." },
  { id: "cookies", title: "Cookies i podobne technologie", version: "1.0", effectiveAt: EFFECTIVE_AT, publishedAt: EFFECTIVE_AT, status: "active", fileName: "fiszy-cookies-v1.0-2026-09-27.md", content: "# Cookies i podobne technologie\n\nWersja 1.0 · obowiązuje od 27.09.2026\n\nCookies niezbędne obsługują logowanie, bezpieczeństwo i ustawienia. Dobrowolna analityka jest używana zgodnie z wyborem użytkownika." },
  { id: "reklamacje", title: "Reklamacje i zwroty", version: "1.0", effectiveAt: EFFECTIVE_AT, publishedAt: EFFECTIVE_AT, status: "active", fileName: "fiszy-reklamacje-i-zwroty-v1.0-2026-09-27.md", content: "# Reklamacje i zwroty Fiszy\n\nWersja 1.0 · obowiązuje od 27.09.2026\n\nKonsument może odstąpić od umowy w ciągu 14 dni od otrzymania produktu, z wyjątkami przewidzianymi przez prawo. Koszt odesłania produktu ponosi konsument, chyba że uzgodnimy inaczej." },
] satisfies LegalDocumentVersion[]).map((item) => ({ ...item, content: snapshot(item.id) }));

export function findLegalDocumentVersion(id: string, version: string) {
  return legalDocumentHistory.find((item) => item.id === id && item.version === version) ?? null;
}
